name: Update README
on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
     - name: GitHub - Activity - Readme
       uses: jamesgeorge007/github-activity-readme@v0.4.4
            